<?php

// Email Configuration
// Auto-generated by setup wizard

return array (
  'smtp' => 
  array (
    'host' => 'smtp.gmail.com',
    'port' => 587,
    'secure' => 'tls',
    'username' => 'novaguard3@gmail.com',
    'password' => 'grvn uhco rbft jzak',
    'from_email' => '',
    'from_name' => 'NovaGuard System',
  ),
);
?>