<?php
session_start();

// Handle form submission
if ($_POST) {
    $config = [
        'smtp' => [
            'host' => 'smtp.gmail.com',
            'port' => 587,
            'secure' => 'tls',
            'username' => $_POST['username'] ?? '',
            'password' => $_POST['password'] ?? '',
            'from_email' => $_POST['from_email'] ?? $_POST['username'] ?? '',
            'from_name' => $_POST['from_name'] ?? 'NovaGuard System'
        ]
    ];
    
    // Save configuration
    $configContent = "<?php\n\n// Email Configuration\n// Auto-generated by setup wizard\n\nreturn " . var_export($config, true) . ";\n?>";
    
    if (file_put_contents(__DIR__ . '/config.php', $configContent)) {
        $success = "Email configuration saved successfully!";
    } else {
        $error = "Failed to save configuration. Please check file permissions.";
    }
}

// Load existing config if available
$existingConfig = [];
if (file_exists(__DIR__ . '/config.php')) {
    $existingConfig = require __DIR__ . '/config.php';
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Setup - NovaGuard</title>
    <link rel="stylesheet" href="styles/style.css">
</head>
<body>
    <div class="container">
        <h1>NovaGuard Email Setup</h1>
        <div class="setup-panel">
            <?php if (isset($success)): ?>
                <div class="success-message"><?php echo $success; ?></div>
            <?php endif; ?>
            <?php if (isset($error)): ?>
                <div class="error-message"><?php echo $error; ?></div>
            <?php endif; ?>
            <form method="post" class="setup-form">
                <h3>Gmail SMTP Configuration</h3>
                <div class="form-group">
                    <label for="username">Gmail Address:</label>
                    <input type="email" name="username" id="username" 
                           value="<?php echo $existingConfig['smtp']['username'] ?? ''; ?>" 
                           placeholder="your-email@gmail.com" required>
                    <small>This is the Gmail account that will send emails</small>
                </div>
                <div class="form-group">
                    <label for="password">App Password:</label>
                    <input type="password" name="password" id="password" 
                           value="<?php echo $existingConfig['smtp']['password'] ?? ''; ?>" 
                           placeholder="16-character app password" required>
                    <small>
                        <strong>Important:</strong> Use an App Password, not your regular Gmail password.<br>
                        <a href="https://support.google.com/accounts/answer/185833" target="_blank">
                            How to generate an App Password
                        </a>
                    </small>
                </div>
                <div class="form-group">
                    <label for="from_email">From Email (optional):</label>
                    <input type="email" name="from_email" id="from_email" 
                           value="<?php echo $existingConfig['smtp']['from_email'] ?? ''; ?>" 
                           placeholder="Leave empty to use Gmail address">
                    <small>Email address that appears as the sender (defaults to Gmail address)</small>
                </div>
                <div class="form-group">
                    <label for="from_name">From Name (optional):</label>
                    <input type="text" name="from_name" id="from_name" 
                           value="<?php echo $existingConfig['smtp']['from_name'] ?? 'NovaGuard System'; ?>" 
                           placeholder="NovaGuard System">
                    <small>Name that appears as the sender</small>
                </div>
                <div class="form-actions">
                    <button type="submit">Save Configuration</button>
                </div>
            </form>
            <div class="setup-instructions">
                <h4>Setup Instructions:</h4>
                <ol>
                    <li>Enable 2-Step Verification on your Gmail account</li>
                    <li>Generate an App Password for "Mail"</li>
                    <li>Enter your Gmail address and App Password above</li>
                    <li>Click "Save Configuration"</li>
                    <li>Test the email functionality</li>
                </ol>
            </div>
        </div>
    </div>
</body>
</html> 